apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack2matrix
  labels:
    app: slack2matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack2matrix
  template:
    metadata:
      labels:
        app: slack2matrix
    spec:
      automountServiceAccountToken: false
      containers:
      - name: slack2matrix
        image: justinbarrick/matrixctl:latest
        args:
        - slack2matrix
        - defaultchannel
        env:
        - name: MATRIX_CONFIG
          value: /app/config.json
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
      volumes:
      - name: config-volume
        secrets:
          name: slack2matrix
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 1.1.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: slack2matrix
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: slack2matrix
